# Generated by Django 5.2.17 on 2026-09-24 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0002_unit_is_now_device'),
        ('inventory', '0007_stockmove_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(choices=[('in_house', 'Made by us'), ('external', 'External')], default='in_house', max_length=20)),
                ('role', models.CharField(choices=[('product', 'Product (unit we build)'), ('test_equipment', 'Test equipment'), ('power_supply', 'Power supply'), ('electronic_load', 'Electronic / test load'), ('measurement', 'Measurement (DMM, scope, ...)'), ('signal_source', 'Signal generator / source'), ('other', 'Other')], default='product', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#3b7dd8', help_text='Colour of the device in the harness designer.', max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.OneToOneField(blank=True, limit_choices_to={'assembly_type': 'device'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='assemblies.assembly')),
                ('responsible', models.ForeignKey(blank=True, help_text='Owner; verifies wiring to this device in harnesses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(help_text='e.g. J01 (jack on the device) or P01 (plug).', max_length=20)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Where it sits in the harness designer.', max_length=5)),
                ('description', models.CharField(blank=True, help_text='e.g. "Main power in".', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(blank=True, help_text='The connector part, e.g. a D-sub 25 socket. Gives the interconnect family and gender.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_connectors', to='inventory.part', verbose_name='Physical connector')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='devices.device')),
            ],
            options={
                'ordering': ['position', 'designator'],
            },
        ),
        migrations.CreateModel(
            name='DeviceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='devices.device')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('label', models.CharField(help_text='The number printed on the connector, e.g. 13.', max_length=20)),
                ('signal', models.CharField(blank=True, help_text='e.g. PWR, GND, CAN_H.', max_length=50)),
                ('set_name', models.CharField(blank=True, help_text='Groups pins wired together, e.g. "Set 1".', max_length=50, verbose_name='Pin set')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='devices.connector')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='connector',
            constraint=models.UniqueConstraint(fields=('device', 'designator'), name='unique_connector_designator'),
        ),
        migrations.AddConstraint(
            model_name='deviceversion',
            constraint=models.UniqueConstraint(fields=('device', 'version'), name='unique_device_version'),
        ),
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.UniqueConstraint(fields=('connector', 'position'), name='unique_pin_position'),
        ),
    ]
