# Generated by Django 5.2.17 on 2026-09-25 03:45

from django.db import migrations


def strip_sets_from_versions(apps, schema_editor):
    """Pin sets are gone; drop them from saved versions too, so a device's
    current definition still matches its current version (no spurious bump)."""
    DeviceVersion = apps.get_model('devices', 'DeviceVersion')
    for version in DeviceVersion.objects.all():
        changed = False
        for connector in version.data.get('connectors', []):
            for pin in connector.get('pins', []):
                if 'set' in pin:
                    del pin['set']
                    changed = True
        if changed:
            version.save(update_fields=['data'])


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(strip_sets_from_versions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pin',
            name='set_name',
        ),
    ]
