# Generated by Django 5.2.17 on 2026-09-27 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_pin_sets'),
        ('inventory', '0008_remove_interconnect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='part',
            field=models.ForeignKey(blank=True, help_text='The connector part, e.g. a D-sub 25 socket. Its description is shown as the connector type in harnesses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_connectors', to='inventory.part', verbose_name='Physical connector'),
        ),
    ]
