# Generated by Django 5.2.17 on 2026-09-30 05:27

import django.db.models.deletion
from django.db import migrations, models


def signals_from_pins(apps, schema_editor):
    """The shared signal list starts with every signal the pins already use."""
    Pin = apps.get_model('devices', 'Pin')
    Signal = apps.get_model('devices', 'Signal')
    seen = {}
    for name in Pin.objects.exclude(signal='').values_list('signal', flat=True):
        name = name.strip()
        if name and name.upper() not in seen:
            seen[name.upper()] = name
    Signal.objects.bulk_create([Signal(name=n) for n in sorted(seen.values())])


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_connector_part_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['from_pin__connector__position', 'from_pin__position'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='connector',
            name='details',
            field=models.CharField(blank=True, help_text='When no part is set: what the connector is, e.g. "M12 8-pin A-coded".', max_length=200, verbose_name='Connector details'),
        ),
        migrations.AddField(
            model_name='connector',
            name='gender',
            field=models.CharField(blank=True, choices=[('pin', 'Pin (male)'), ('socket', 'Socket (female)')], max_length=10),
        ),
        migrations.AddField(
            model_name='pin',
            name='set_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Set'),
        ),
        migrations.AddField(
            model_name='pin',
            name='set_type',
            field=models.CharField(blank=True, choices=[('straight', 'Straight'), ('twisted', 'Twisted'), ('shielded', 'Shielded'), ('twisted_shielded', 'Twisted shielded')], max_length=20),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag',
            field=models.CharField(blank=True, help_text='A name for what the pin carries, e.g. MOTOR_A+. Unique within the connector.', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='role',
            field=models.CharField(choices=[('product', 'Product (unit we build)'), ('test_equipment', 'Test equipment'), ('power_supply', 'Power supply'), ('electronic_load', 'Electronic / test load'), ('measurement', 'Measurement (DMM, scope, ...)'), ('signal_source', 'Signal generator / source'), ('interconnect', 'Interconnect (adapter, breakout, extension)'), ('other', 'Other')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='pin',
            name='signal',
            field=models.CharField(blank=True, help_text='One of the signals in Devices > Signals.', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.UniqueConstraint(condition=models.Q(('tag', ''), _negated=True), fields=('connector', 'tag'), name='unique_pin_tag_per_connector'),
        ),
        migrations.AddField(
            model_name='pinmap',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_maps', to='devices.device'),
        ),
        migrations.AddField(
            model_name='pinmap',
            name='from_pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps_out', to='devices.pin'),
        ),
        migrations.AddField(
            model_name='pinmap',
            name='to_pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps_in', to='devices.pin'),
        ),
        migrations.AddConstraint(
            model_name='pinmap',
            constraint=models.UniqueConstraint(fields=('from_pin', 'to_pin'), name='unique_pin_map'),
        ),
        migrations.RunPython(signals_from_pins, migrations.RunPython.noop),
    ]
