# Generated by Django 5.2.17 on 2026-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_connector_tag_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='details',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='gender',
        ),
        migrations.AlterField(
            model_name='connector',
            name='description',
            field=models.CharField(blank=True, help_text='What the connector is for, e.g. "Main power in".', max_length=200, verbose_name='Function'),
        ),
    ]
