# Generated by Django 5.2.17 on 2026-09-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_alter_part_options_category_parent_and_more'),
        ('tasks', '0003_task_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assembly_type', models.CharField(choices=[('generic', 'Generic'), ('unit', 'Unit'), ('harness', 'Harness'), ('plate_stack', 'Plate stack')], default='generic', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='manufacturing', max_length=20)),
                ('version', models.CharField(default='1', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('build_instructions', models.TextField(blank=True)),
                ('usage_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'assemblies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='assemblies.assembly')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_link', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assemblies.assembly')),
                ('child_assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='assemblies.assembly')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_uses', to='inventory.part')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('child_assembly__isnull', True), ('part__isnull', False)), models.Q(('child_assembly__isnull', False), ('part__isnull', True)), _connector='OR'), name='component_is_part_xor_assembly'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='component_quantity_positive')],
            },
        ),
    ]
