# Generated by Django 5.2.17 on 2026-09-24 00:15

from django.db import migrations, models


def unit_to_device(apps, schema_editor):
    apps.get_model('assemblies', 'Assembly').objects.filter(assembly_type='unit').update(assembly_type='device')


def device_to_unit(apps, schema_editor):
    apps.get_model('assemblies', 'Assembly').objects.filter(assembly_type='device').update(assembly_type='unit')


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='assembly_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('device', 'Device'), ('harness', 'Harness'), ('plate_stack', 'Plate stack')], default='generic', max_length=20, verbose_name='Type'),
        ),
        migrations.RunPython(unit_to_device, device_to_unit),
    ]
