# Generated by Django 5.2.17 on 2026-09-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_to_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['part_number']},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='part',
            name='interconnect_family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='interconnect_gender',
            field=models.CharField(blank=True, choices=[('', '(unspecified)'), ('male', 'Male'), ('female', 'Female'), ('genderless', 'Genderless')], max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='part',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to archive the part.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_value', models.CharField(blank=True, help_text='Example or typical value, shown as a hint on parts.', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='inventory.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.location')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='part',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.location'),
        ),
        migrations.CreateModel(
            name='PartAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_values', to='inventory.attribute')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='inventory.part')),
            ],
            options={
                'ordering': ['attribute__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_attribute_per_category'),
        ),
        migrations.AddConstraint(
            model_name='partattributevalue',
            constraint=models.UniqueConstraint(fields=('part', 'attribute'), name='unique_value_per_part_attribute'),
        ),
    ]
