# Generated by Django 5.2.17 on 2026-09-23 23:54

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_unit_cost(apps, schema_editor):
    """Existing moves take the part's current cost: the best we know."""
    StockMove = apps.get_model('inventory', 'StockMove')
    Part = apps.get_model('inventory', 'Part')
    StockMove.objects.update(unit_cost=Subquery(Part.objects.filter(pk=OuterRef('part_id')).values('cost')[:1]))


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_part_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.RunPython(backfill_unit_cost, migrations.RunPython.noop),
    ]
