# Generated by Django 5.2.17 on 2026-09-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockmove_unit_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmove',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
