# Generated by Django 5.2.17 on 2026-09-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockmove_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='interconnect_family',
        ),
        migrations.RemoveField(
            model_name='part',
            name='interconnect_gender',
        ),
    ]
