# Generated by Django 5.2.17 on 2026-09-29 23:55

from django.db import migrations, models


def fill_paths(apps, schema_editor):
    """Store every existing location's path (its code starts out empty: no labels yet)."""
    Location = apps.get_model('inventory', 'Location')
    nodes = {n.pk: n for n in Location.objects.all()}

    def path(node, seen=()):
        parent = nodes.get(node.parent_id)
        if parent is None or parent.pk in seen:
            return node.name
        return f'{path(parent, (*seen, node.pk))} > {node.name}'

    for node in nodes.values():
        node.path = path(node)
    Location.objects.bulk_update(nodes.values(), ['path'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_interconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='label',
            field=models.CharField(blank=True, help_text="Short code, e.g. A or 1. A location's code joins the labels down the tree: rack row A, rack 1, shelf A is A1A.", max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='path',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('label', ''), _negated=True), fields=('parent', 'label'), name='unique_location_label_per_parent'),
        ),
        migrations.RunPython(fill_paths, migrations.RunPython.noop),
    ]
