# Generated by Django 5.2.17 on 2026-09-30 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_location_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='move_type',
            field=models.CharField(choices=[('in', 'Receipt'), ('out', 'Issue'), ('adjust', 'Adjustment'), ('transfer', 'Transfer')], max_length=10, verbose_name='Type'),
        ),
    ]
