# Generated by Django 5.2.17 on 2026-09-23 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0004_department'),
        ('users', '0002_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget_number', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='users.department')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='budgets.budget')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='budgets.budget')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_link', to='tasks.task')),
            ],
        ),
    ]
