# Generated by Django 5.2.17 on 2026-10-01 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='location',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='stock.location'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='received_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('partial', 'Partly received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=20),
        ),
    ]
